name: Deploy dev
on:
  push:
    branches:
      - feature/infra
jobs:
  deploy-dev:
    uses: ./.github/workflows/deploy.yaml
    with:
      stack: suomensuurinwappu-stack-dev
      environment: development
