name: Deploy prod
on:
  push:
    branches:
      - release/**
concurrency:
  group: prod
jobs:
  deploy-prod:
    uses: ./.github/workflows/deploy.yaml
    with:
      STACK: suomensuurinwappu-stack-prod
      AWS_REGION: eu-north-1
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      REACT_APP_STORYBLOK_TOKEN: ${{ secrets.REACT_APP_STORYBLOK_TOKEN_PROD }}
      REACT_APP_GA_MEASUREMENT_ID: ${{ secrest.REACT_APP_GA_MEASUREMENT_ID }}
